### PR TITLE
Add a publisher for handling fanouts to an exchange

### PR DESCRIPTION
**Pull request by jcox-dev**
To implement a publisher / subscriber model with multiple consumers we require a publisher that publishes to an exchange.

Renamed publisher.py -> publishers.py and added a new class that duplicates a lot of existing functionality to support publishing to an exchange.

### CODE REVIEW

**Comment by jcox-dev** [comment]
[US042: Create and View 'Ready for Review' State of a CE [M]](https://trello.com/c/Fb6CS3es/36-us042-create-and-view-ready-for-review-state-of-a-ce-m)

**Comment by jcox-dev** [comment]
[Add ExchangePublisher to sdc-rabbit for handling fanout messages](https://trello.com/c/e4DJqBPe/58-add-exchangepublisher-to-sdc-rabbit-for-handling-fanout-messages)

**Comment by gemmai95** [comment]
This change will break SDX-collect this has been flagged with SDX and they are going to make the change.

**Comment by JamesGardiner** [comment]
The changes that @gemmai95 mentioned now have open PRs in the relevant repos.

**Comment by jcox-dev** [comment]
@gemmai95 thanks for spotting that 😄

**Pull request merged**
